version: '3.9'

services:
  app:
    build: ./
    env_file:
      - .env
    volumes:
     - ./:/app
     - /app/node_modules
    ports:
      - 8080:80
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    volumes:
      - db:/data/db
volumes:
  db:
