apiVersion: v1
kind: Service
metadata:
  name: nodejs-measurements-app-service
spec:
  selector:
    app: nodejs-measurements-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: LoadBalancer
